In [59]:
import pandas as pd

In [60]:
df = pd.read_csv("/content/covid_toy.csv")

In [61]:
df.head(7)

   age  gender  fever   cough       city has_covid
0   60    Male  103.0    Mild    Kolkata        No
1   27    Male  100.0    Mild      Delhi       Yes
2   42    Male  101.0    Mild      Delhi        No
3   31  Female   98.0    Mild    Kolkata        No
4   65  Female  101.0    Mild     Mumbai        No
5   84  Female    NaN    Mild  Bangalore       Yes
6   14    Male  101.0  Strong  Bangalore        No

In [62]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [63]:

df["fever"] = df["fever"].fillna(df['fever'].mean())

In [64]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [65]:


df["fever"].mean()

np.float64(100.84444444444445)

In [66]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [67]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [68]:
df['gender'] = df['gender'].map({'Female':1,'Male':0})

In [69]:
df.head(7)

   age  gender       fever   cough       city has_covid
0   60       0  103.000000    Mild    Kolkata        No
1   27       0  100.000000    Mild      Delhi       Yes
2   42       0  101.000000    Mild      Delhi        No
3   31       1   98.000000    Mild    Kolkata        No
4   65       1  101.000000    Mild     Mumbai        No
5   84       1  100.844444    Mild  Bangalore       Yes
6   14       0  101.000000  Strong  Bangalore        No

In [70]:
df['cough'] = df['cough'].map({"Mild":0,"Strong":1})

In [71]:
df.head(7)

   age  gender       fever  cough       city has_covid
0   60       0  103.000000      0    Kolkata        No
1   27       0  100.000000      0      Delhi       Yes
2   42       0  101.000000      0      Delhi        No
3   31       1   98.000000      0    Kolkata        No
4   65       1  101.000000      0     Mumbai        No
5   84       1  100.844444      0  Bangalore       Yes
6   14       0  101.000000      1  Bangalore        No

In [72]:
df['has_covid'] = df['has_covid'].map({'No':1,'Yes':0})

In [73]:
df

    age  gender  fever  cough       city  has_covid
0    60       0  103.0      0    Kolkata          1
1    27       0  100.0      0      Delhi          0
2    42       0  101.0      0      Delhi          1
3    31       1   98.0      0    Kolkata          1
4    65       1  101.0      0     Mumbai          1
..  ...     ...    ...    ...        ...        ...
95   12       1  104.0      0  Bangalore          1
96   51       1  101.0      1    Kolkata          0
97   20       1  101.0      0  Bangalore          1
98    5       1   98.0      1     Mumbai          1
99   10       1   98.0      1    Kolkata          0

[100 rows x 6 columns]

In [74]:
df[['fever','has_covid']]

    fever  has_covid
0   103.0          1
1   100.0          0
2   101.0          1
3    98.0          1
4   101.0          1
..    ...        ...
95  104.0          1
96  101.0          0
97  101.0          1
98   98.0          1
99   98.0          0

[100 rows x 2 columns]

In [75]:
df.head(3)

   age  gender  fever  cough     city  has_covid
0   60       0  103.0      0  Kolkata          1
1   27       0  100.0      0    Delhi          0
2   42       0  101.0      0    Delhi          1

In [76]:
df['fever'] = df['fever'].astype(int)

In [77]:
df

    age  gender  fever  cough       city  has_covid
0    60       0    103      0    Kolkata          1
1    27       0    100      0      Delhi          0
2    42       0    101      0      Delhi          1
3    31       1     98      0    Kolkata          1
4    65       1    101      0     Mumbai          1
..  ...     ...    ...    ...        ...        ...
95   12       1    104      0  Bangalore          1
96   51       1    101      1    Kolkata          0
97   20       1    101      0  Bangalore          1
98    5       1     98      1     Mumbai          1
99   10       1     98      1    Kolkata          0

[100 rows x 6 columns]

In [78]:
df['age'] = df['age'].astype(float)

In [79]:
df

     age  gender  fever  cough       city  has_covid
0   60.0       0    103      0    Kolkata          1
1   27.0       0    100      0      Delhi          0
2   42.0       0    101      0      Delhi          1
3   31.0       1     98      0    Kolkata          1
4   65.0       1    101      0     Mumbai          1
..   ...     ...    ...    ...        ...        ...
95  12.0       1    104      0  Bangalore          1
96  51.0       1    101      1    Kolkata          0
97  20.0       1    101      0  Bangalore          1
98   5.0       1     98      1     Mumbai          1
99  10.0       1     98      1    Kolkata          0

[100 rows x 6 columns]

In [80]:
df['fever'][1:3] = 50

/tmp/ipykernel_1351/146693501.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['fever'][1:3] = 50
/tmp/ipykernel_1351/146693501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fever'][1:3] = 50

In [81]:
df.head(3)

    age  gender  fever  cough     city  has_covid
0  60.0       0    103      0  Kolkata          1
1  27.0       0     50      0    Delhi          0
2  42.0       0     50      0    Delhi          1

In [82]:
df.rename(columns={"cough":"updated_cough"})

     age  gender  fever  updated_cough       city  has_covid
0   60.0       0    103              0    Kolkata          1
1   27.0       0     50              0      Delhi          0
2   42.0       0     50              0      Delhi          1
3   31.0       1     98              0    Kolkata          1
4   65.0       1    101              0     Mumbai          1
..   ...     ...    ...            ...        ...        ...
95  12.0       1    104              0  Bangalore          1
96  51.0       1    101              1    Kolkata          0
97  20.0       1    101              0  Bangalore          1
98   5.0       1     98              1     Mumbai          1
99  10.0       1     98              1    Kolkata          0

[100 rows x 6 columns]

In [83]:
df.rename(columns={"age":"new_age"})

    new_age  gender  fever  cough       city  has_covid
0      60.0       0    103      0    Kolkata          1
1      27.0       0     50      0      Delhi          0
2      42.0       0     50      0      Delhi          1
3      31.0       1     98      0    Kolkata          1
4      65.0       1    101      0     Mumbai          1
..      ...     ...    ...    ...        ...        ...
95     12.0       1    104      0  Bangalore          1
96     51.0       1    101      1    Kolkata          0
97     20.0       1    101      0  Bangalore          1
98      5.0       1     98      1     Mumbai          1
99     10.0       1     98      1    Kolkata          0

[100 rows x 6 columns]

In [89]:
df.rename(columns={"fever":"new_fever","gender":"new_gender","cough":"new_cough","city":"new_city"})

     age  new_gender  new_fever  new_cough   new_city  has_covid
0   60.0           0        103          0    Kolkata          1
1   27.0           0         50          0      Delhi          0
2   42.0           0         50          0      Delhi          1
3   31.0           1         98          0    Kolkata          1
4   65.0           1        101          0     Mumbai          1
..   ...         ...        ...        ...        ...        ...
95  12.0           1        104          0  Bangalore          1
96  51.0           1        101          1    Kolkata          0
97  20.0           1        101          0  Bangalore          1
98   5.0           1         98          1     Mumbai          1
99  10.0           1         98          1    Kolkata          0

[100 rows x 6 columns]

In [95]:
df['new_city'] = df['city'].where(df['city']=="Delhi",other=0)

In [96]:
df.head(10)

    age  gender  fever  cough   city  has_covid new_city
0  60.0       0    103      0      0          1        0
1  27.0       0     50      0  Delhi          0    Delhi
2  42.0       0     50      0  Delhi          1    Delhi
3  31.0       1     98      0      0          1        0
4  65.0       1    101      0      0          1        0
5  84.0       1    100      0      0          0        0
6  14.0       0    101      1      0          1        0
7  20.0       1    100      1      0          0        0
8  19.0       1    100      1      0          1        0
9  64.0       1    101      0  Delhi          1    Delhi

In [98]:
df['has_covid'] = df['has_covid'].where(df['has_covid']==0,other="positive")

In [99]:
df.head(10)

    age  gender  fever  cough   city has_covid new_city
0  60.0       0    103      0      0  positive        0
1  27.0       0     50      0  Delhi         0    Delhi
2  42.0       0     50      0  Delhi  positive    Delhi
3  31.0       1     98      0      0  positive        0
4  65.0       1    101      0      0  positive        0
5  84.0       1    100      0      0         0        0
6  14.0       0    101      1      0  positive        0
7  20.0       1    100      1      0         0        0
8  19.0       1    100      1      0  positive        0
9  64.0       1    101      0  Delhi  positive    Delhi

In [100]:
df.to_csv("covid_patient_records.csv",index=False)